# Generated by Django 3.0.6 on 2024-06-23 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0003_user_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='boss_id',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee', to='invoice.User', verbose_name='Company'),
        ),
    ]
