# Generated by Django 3.0.6 on 2024-06-25 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0008_upfile_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upfile',
            name='file',
            field=models.FileField(blank=True, upload_to='invoices_files/'),
        ),
    ]
