# Generated by Django 4.2.13 on 2024-06-28 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoice", "0011_company_abn"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="ABN",
            field=models.CharField(max_length=20, verbose_name="ABN"),
        ),
    ]
