# Generated by Django 4.2.13 on 2024-07-01 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("invoice", "0012_alter_company_abn"),
    ]

    operations = [
        migrations.CreateModel(
            name="GUIFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=30)),
                ("abn", models.CharField(max_length=20, verbose_name="ABN")),
                (
                    "additional_request",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Additional Request",
                    ),
                ),
                (
                    "approver",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Additional Request",
                    ),
                ),
                (
                    "approver_email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        null=True,
                        verbose_name="Approver Email",
                    ),
                ),
                (
                    "bPayRef",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="bPay Reference",
                    ),
                ),
                (
                    "bPaycode",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="bPay Code"
                    ),
                ),
                (
                    "bankAccount",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Bank Account",
                    ),
                ),
                (
                    "bankBranch",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Bank Branch",
                    ),
                ),
                (
                    "bank_details",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Bank Details",
                    ),
                ),
                ("changed", models.BooleanField(default=True, verbose_name="Changed")),
                (
                    "charge",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        verbose_name="Charge",
                    ),
                ),
                (
                    "company_invoiced",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Company Invoiced",
                    ),
                ),
                (
                    "delivery_to",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Delivery To",
                    ),
                ),
                (
                    "delivery_to_address",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Delivery To Address",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "document_subtype",
                    models.IntegerField(default=1, verbose_name="Document Subtype"),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="Email"
                    ),
                ),
                (
                    "email_to",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="Email"
                    ),
                ),
                (
                    "expense_claim",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Expense Claim",
                    ),
                ),
                (
                    "from_email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="From Email"
                    ),
                ),
                (
                    "glcode_option",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="GL Code Option",
                    ),
                ),
                (
                    "glcode_text",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="GL Code Text",
                    ),
                ),
                (
                    "invoiceDate",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Invoice Date"
                    ),
                ),
                (
                    "invoiceNumber",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Invoice Number",
                    ),
                ),
                (
                    "invoice_to",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Invoice To"
                    ),
                ),
                (
                    "invoice_to_address",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Invoice To Address",
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Location"
                    ),
                ),
                (
                    "purchaseOrder",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Purchase Order",
                    ),
                ),
                (
                    "require_bank_details",
                    models.BooleanField(
                        default=False, verbose_name="Require Bank Details"
                    ),
                ),
                (
                    "require_email",
                    models.BooleanField(default=False, verbose_name="Require Email"),
                ),
                (
                    "supplier",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Supplier"
                    ),
                ),
                (
                    "supplier_address",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Supplier Address",
                    ),
                ),
                (
                    "supplier_id",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Supplier ID",
                    ),
                ),
                (
                    "tax",
                    models.DecimalField(
                        decimal_places=2, default=0.0, max_digits=10, verbose_name="Tax"
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        verbose_name="Total",
                    ),
                ),
                (
                    "tracking",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Tracking"
                    ),
                ),
                (
                    "tracking_option",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Tracking Option",
                    ),
                ),
                (
                    "userid",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="GUIFiles",
                        to="invoice.user",
                    ),
                ),
            ],
        ),
    ]
