# Generated by Django 4.2.13 on 2024-07-01 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("invoice", "0013_guifile"),
    ]

    operations = [
        migrations.RenameField(
            model_name="upfile",
            old_name="title",
            new_name="uuid",
        ),
    ]
