# Generated by Django 4.2.13 on 2024-07-02 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("invoice", "0014_rename_title_upfile_uuid"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="reset_password_sent_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Reset Password Sent At"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="reset_password_token",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Reset Password Token",
            ),
        ),
        migrations.AlterField(
            model_name="guifile",
            name="additional_request",
            field=models.CharField(max_length=255, verbose_name="Additional Request"),
        ),
        migrations.AlterField(
            model_name="guifile",
            name="approver",
            field=models.CharField(max_length=255, verbose_name="Additional Request"),
        ),
        migrations.AlterField(
            model_name="guifile",
            name="approver_email",
            field=models.EmailField(max_length=254, verbose_name="Approver Email"),
        ),
        migrations.AlterField(
            model_name="guifile",
            name="bPayRef",
            field=models.CharField(max_length=255, verbose_name="bPay Reference"),
        ),
        migrations.AlterField(
            model_name="guifile",
            name="bPaycode",
            field=models.CharField(max_length=255, verbose_name="bPay Code"),
        ),
        migrations.AlterField(
            model_name="guifile",
            name="bankAccount",
            field=models.CharField(max_length=255, verbose_name="Bank Account"),
        ),
        migrations.AlterField(
            model_name="guifile",
            name="bankBranch",
            field=models.CharField(max_length=255, verbose_name="Bank Branch"),
        ),
        migrations.AlterField(
            model_name="guifile",
            name="bank_details",
            field=models.CharField(max_length=255, verbose_name="Bank Details"),
        ),
        migrations.AlterField(
            model_name="guifile",
            name="company_invoiced",
            field=models.CharField(max_length=255, verbose_name="Company Invoiced"),
        ),
        migrations.AlterField(
            model_name="guifile",
            name="delivery_to",
            field=models.CharField(max_length=255, verbose_name="Delivery To"),
        ),
        migrations.AlterField(
            model_name="guifile",
            name="delivery_to_address",
            field=models.CharField(max_length=255, verbose_name="Delivery To Address"),
        ),
        migrations.AlterField(
            model_name="guifile",
            name="description",
            field=models.CharField(max_length=255, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="guifile",
            name="email",
            field=models.EmailField(max_length=254, verbose_name="Email"),
        ),
        migrations.AlterField(
            model_name="guifile",
            name="email_to",
            field=models.EmailField(max_length=254, verbose_name="Email"),
        ),
        migrations.AlterField(
            model_name="guifile",
            name="expense_claim",
            field=models.CharField(max_length=255, verbose_name="Expense Claim"),
        ),
        migrations.AlterField(
            model_name="guifile",
            name="from_email",
            field=models.EmailField(max_length=254, verbose_name="From Email"),
        ),
        migrations.AlterField(
            model_name="guifile",
            name="glcode_option",
            field=models.CharField(max_length=255, verbose_name="GL Code Option"),
        ),
        migrations.AlterField(
            model_name="guifile",
            name="glcode_text",
            field=models.CharField(max_length=255, verbose_name="GL Code Text"),
        ),
        migrations.AlterField(
            model_name="guifile",
            name="invoiceDate",
            field=models.DateTimeField(verbose_name="Invoice Date"),
        ),
        migrations.AlterField(
            model_name="guifile",
            name="invoiceNumber",
            field=models.CharField(max_length=255, verbose_name="Invoice Number"),
        ),
        migrations.AlterField(
            model_name="guifile",
            name="invoice_to",
            field=models.CharField(max_length=255, verbose_name="Invoice To"),
        ),
        migrations.AlterField(
            model_name="guifile",
            name="invoice_to_address",
            field=models.CharField(max_length=255, verbose_name="Invoice To Address"),
        ),
        migrations.AlterField(
            model_name="guifile",
            name="location",
            field=models.CharField(max_length=255, verbose_name="Location"),
        ),
        migrations.AlterField(
            model_name="guifile",
            name="purchaseOrder",
            field=models.CharField(max_length=255, verbose_name="Purchase Order"),
        ),
        migrations.AlterField(
            model_name="guifile",
            name="supplier",
            field=models.CharField(max_length=255, verbose_name="Supplier"),
        ),
        migrations.AlterField(
            model_name="guifile",
            name="supplier_address",
            field=models.CharField(max_length=255, verbose_name="Supplier Address"),
        ),
        migrations.AlterField(
            model_name="guifile",
            name="supplier_id",
            field=models.CharField(max_length=255, verbose_name="Supplier ID"),
        ),
        migrations.AlterField(
            model_name="guifile",
            name="tracking",
            field=models.CharField(max_length=255, verbose_name="Tracking"),
        ),
        migrations.AlterField(
            model_name="guifile",
            name="tracking_option",
            field=models.CharField(max_length=255, verbose_name="Tracking Option"),
        ),
        migrations.AlterField(
            model_name="guifile",
            name="userid",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="GUIFiles",
                to="invoice.user",
            ),
        ),
        migrations.AlterField(
            model_name="upfile",
            name="file",
            field=models.FileField(upload_to="invoices_files/"),
        ),
    ]
