# Generated by Django 4.2.13 on 2024-07-05 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("invoice", "0015_user_reset_password_sent_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="guifile",
            name="title",
        ),
        migrations.AlterField(
            model_name="guifile",
            name="userid",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="GUIFiles",
                to="invoice.user",
            ),
        ),
    ]
