# Generated by Django 4.2.13 on 2024-07-05 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoice", "0016_remove_guifile_title_alter_guifile_userid"),
    ]

    operations = [
        migrations.AddField(
            model_name="guifile",
            name="filename",
            field=models.CharField(default=213, max_length=30),
            preserve_default=False,
        ),
    ]
