# Generated by Django 4.2.13 on 2024-07-05 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoice", "0017_guifile_filename"),
    ]

    operations = [
        migrations.AddField(
            model_name="guifile",
            name="uuid",
            field=models.CharField(default=12321323, max_length=30),
            preserve_default=False,
        ),
    ]
