# Generated by Django 4.2.13 on 2024-07-06 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("invoice", "0018_guifile_uuid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="token",
        ),
    ]
