# Generated by Django 4.2.13 on 2024-07-07 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("invoice", "0020_rename_is_admin_user_is_staff"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="guifile",
            unique_together={("userid", "filename")},
        ),
        migrations.AlterUniqueTogether(
            name="upfile",
            unique_together={("userid", "file")},
        ),
    ]
