# Generated by Django 4.2.13 on 2024-07-08 09:58

from django.db import migrations, models
import invoice.models


class Migration(migrations.Migration):

    dependencies = [
        ("invoice", "0021_alter_guifile_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="upfile",
            name="file",
            field=models.FileField(upload_to=invoice.models.user_directory_path),
        ),
    ]
