# Generated by Django 4.2.13 on 2024-07-10 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoice", "0022_alter_upfile_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="upfile",
            name="is_correct",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="upfile",
            name="is_validated",
            field=models.BooleanField(default=False),
        ),
    ]
