# Generated by Django 4.2.13 on 2024-07-19 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("invoice", "0023_upfile_is_correct_upfile_is_validated"),
    ]

    operations = [
        migrations.RenameField(
            model_name="guifile",
            old_name="supplier",
            new_name="supplier_name",
        ),
    ]
