# Generated by Django 4.2.13 on 2024-07-20 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("invoice", "0024_rename_supplier_guifile_supplier_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="guifile",
            old_name="supplier_name",
            new_name="supplier",
        ),
    ]
