# Generated by Django 4.2.13 on 2024-07-20 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoice", "0025_rename_supplier_name_guifile_supplier"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=255)),
                ("price", models.CharField(max_length=20)),
                ("quantity", models.IntegerField()),
                ("net", models.CharField(max_length=20)),
                ("vat", models.CharField(max_length=10)),
                ("gross", models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name="guifile",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="guifile",
            name="address",
            field=models.CharField(default="sss", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="guifile",
            name="country_name",
            field=models.CharField(default="sss", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="guifile",
            name="customer_name",
            field=models.CharField(default="111", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="guifile",
            name="important_text",
            field=models.TextField(default="sss"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="guifile",
            name="issue_date",
            field=models.DateField(default="2017-12-21"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="guifile",
            name="items",
            field=models.JSONField(default=list),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="guifile",
            name="manager",
            field=models.CharField(default="ss", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="guifile",
            name="purchase_id",
            field=models.CharField(default="11", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="guifile",
            name="subtotal",
            field=models.CharField(default="111", max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="guifile",
            name="terms",
            field=models.CharField(default="111", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="guifile",
            name="total_price",
            field=models.CharField(default="111", max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="guifile",
            name="vat_number",
            field=models.CharField(default="111", max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="guifile",
            name="vat_total",
            field=models.CharField(default="111", max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="guifile",
            name="id",
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.RemoveField(
            model_name="guifile",
            name="abn",
        ),
        migrations.RemoveField(
            model_name="guifile",
            name="additional_request",
        ),
        migrations.RemoveField(
            model_name="guifile",
            name="approver",
        ),
        migrations.RemoveField(
            model_name="guifile",
            name="approver_email",
        ),
        migrations.RemoveField(
            model_name="guifile",
            name="bPayRef",
        ),
        migrations.RemoveField(
            model_name="guifile",
            name="bPaycode",
        ),
        migrations.RemoveField(
            model_name="guifile",
            name="bankAccount",
        ),
        migrations.RemoveField(
            model_name="guifile",
            name="bankBranch",
        ),
        migrations.RemoveField(
            model_name="guifile",
            name="bank_details",
        ),
        migrations.RemoveField(
            model_name="guifile",
            name="changed",
        ),
        migrations.RemoveField(
            model_name="guifile",
            name="charge",
        ),
        migrations.RemoveField(
            model_name="guifile",
            name="company_invoiced",
        ),
        migrations.RemoveField(
            model_name="guifile",
            name="delivery_to",
        ),
        migrations.RemoveField(
            model_name="guifile",
            name="delivery_to_address",
        ),
        migrations.RemoveField(
            model_name="guifile",
            name="description",
        ),
        migrations.RemoveField(
            model_name="guifile",
            name="document_subtype",
        ),
        migrations.RemoveField(
            model_name="guifile",
            name="email",
        ),
        migrations.RemoveField(
            model_name="guifile",
            name="email_to",
        ),
        migrations.RemoveField(
            model_name="guifile",
            name="expense_claim",
        ),
        migrations.RemoveField(
            model_name="guifile",
            name="filename",
        ),
        migrations.RemoveField(
            model_name="guifile",
            name="from_email",
        ),
        migrations.RemoveField(
            model_name="guifile",
            name="glcode_option",
        ),
        migrations.RemoveField(
            model_name="guifile",
            name="glcode_text",
        ),
        migrations.RemoveField(
            model_name="guifile",
            name="invoiceDate",
        ),
        migrations.RemoveField(
            model_name="guifile",
            name="invoiceNumber",
        ),
        migrations.RemoveField(
            model_name="guifile",
            name="invoice_to",
        ),
        migrations.RemoveField(
            model_name="guifile",
            name="invoice_to_address",
        ),
        migrations.RemoveField(
            model_name="guifile",
            name="location",
        ),
        migrations.RemoveField(
            model_name="guifile",
            name="purchaseOrder",
        ),
        migrations.RemoveField(
            model_name="guifile",
            name="require_bank_details",
        ),
        migrations.RemoveField(
            model_name="guifile",
            name="require_email",
        ),
        migrations.RemoveField(
            model_name="guifile",
            name="supplier",
        ),
        migrations.RemoveField(
            model_name="guifile",
            name="supplier_address",
        ),
        migrations.RemoveField(
            model_name="guifile",
            name="supplier_id",
        ),
        migrations.RemoveField(
            model_name="guifile",
            name="tax",
        ),
        migrations.RemoveField(
            model_name="guifile",
            name="total",
        ),
        migrations.RemoveField(
            model_name="guifile",
            name="tracking",
        ),
        migrations.RemoveField(
            model_name="guifile",
            name="tracking_option",
        ),
        migrations.RemoveField(
            model_name="guifile",
            name="userid",
        ),
        migrations.RemoveField(
            model_name="guifile",
            name="uuid",
        ),
        migrations.AddField(
            model_name="guifile",
            name="orders",
            field=models.ManyToManyField(to="invoice.order"),
        ),
    ]
