# Generated by Django 4.2.13 on 2024-07-20 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoice", "0027_guifile_filename_guifile_userid_guifile_uuid_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="guifile",
            old_name="vat_number",
            new_name="ABN",
        ),
        migrations.RenameField(
            model_name="guifile",
            old_name="customer_name",
            new_name="company_name",
        ),
        migrations.RenameField(
            model_name="guifile",
            old_name="vat_total",
            new_name="qst_total",
        ),
        migrations.RenameField(
            model_name="order",
            old_name="vat",
            new_name="qst",
        ),
        migrations.RemoveField(
            model_name="user",
            name="avatar",
        ),
        migrations.AddField(
            model_name="guifile",
            name="due_date",
            field=models.DateField(default="2017-08-22"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="aqstar",
            field=models.ImageField(
                blank=True, null=True, upload_to="aqstar/", verbose_name="Aqstar"
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="logo",
            field=models.ImageField(
                blank=True, null=True, upload_to="aqstar/", verbose_name="Aqstar"
            ),
        ),
    ]
