# Generated by Django 4.2.13 on 2024-07-21 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoice", "0028_rename_vat_number_guifile_abn_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="guifile",
            name="manager",
        ),
        migrations.AddField(
            model_name="guifile",
            name="account_name",
            field=models.CharField(default="123", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="guifile",
            name="account_num",
            field=models.CharField(default="123", max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="guifile",
            name="bank",
            field=models.CharField(default="chinabank", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="guifile",
            name="bank_branch",
            field=models.CharField(default="beijingRoad", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="guifile",
            name="bsb_num",
            field=models.CharField(default="123", max_length=20),
            preserve_default=False,
        ),
    ]
