# Generated by Django 4.2.13 on 2024-07-22 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoice", "0029_remove_guifile_manager_guifile_account_name_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="guifile",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="guifile",
            name="file_id",
            field=models.CharField(default="1", max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="guifile",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AddConstraint(
            model_name="guifile",
            constraint=models.UniqueConstraint(
                fields=("file_id", "userid"), name="unique_file_user"
            ),
        ),
    ]
