# Generated by Django 4.2.13 on 2024-07-23 11:18

from django.db import migrations, models
import invoice.models


class Migration(migrations.Migration):

    dependencies = [
        ("invoice", "0030_alter_guifile_unique_together_guifile_file_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="aqstar",
        ),
        migrations.AddField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=invoice.models.user_directory_path,
                verbose_name="Avatar",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="bio",
            field=models.TextField(default="Nothing", verbose_name="Bio"),
        ),
    ]
