# Generated by Django 4.2.13 on 2024-07-26 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("invoice", "0032_remove_guifile_unique_file_user_remove_guifile_abn_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="gross",
            new_name="amount",
        ),
        migrations.RemoveField(
            model_name="guifile",
            name="bank_branch",
        ),
    ]
