# Generated by Django 4.2.13 on 2024-07-29 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoice", "0035_upfile_create_date_upfile_email_receiver_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="join_company_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Join Company Date"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="login_date",
            field=models.DateTimeField(auto_now=True, verbose_name="Login Date"),
        ),
    ]
