# Generated by Django 4.2.13 on 2024-07-31 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoice", "0037_draft_create_date_draft_update_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="draft",
            name="due_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="draft",
            name="issue_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
