# Generated by Django 4.2.13 on 2024-07-31 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoice", "0038_alter_draft_due_date_alter_draft_issue_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="upfile",
            name="is_sent",
            field=models.BooleanField(default=False),
        ),
    ]
