# Generated by Django 4.2.13 on 2024-08-01 09:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("invoice", "0039_upfile_is_sent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="upfile",
            name="create_date",
            field=models.DateTimeField(
                blank=True,
                default=django.utils.timezone.now,
                null=True,
                verbose_name="Create Date",
            ),
        ),
    ]
