# Generated by Django 4.2.13 on 2024-08-02 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoice", "0042_alter_draft_account_name_alter_draft_account_num_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="draft",
            name="uuid",
            field=models.CharField(blank=True, default="", max_length=100, null=True),
        ),
    ]
