# Generated by Django 4.2.13 on 2024-08-04 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoice", "0043_alter_draft_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="draft",
            name="orders",
            field=models.ManyToManyField(to="invoice.order"),
        ),
    ]
